let helpers ={
    hidden:{
        display:"none"
    },
    invisible:{
        visibility:"hidden"
    },
    pullLeft:{
        float:"left!important"
    },
    pullRight:{
        float:"right!important"
    },
    show:{
        display:""
    },
    textBig:{
        fontSize:"1.2em"
    },
    textBold:{
        fontWeight:700
    },
    textCenter:{
        textAlign:"center"
    },
    textItalic:{
        fontStyle:"italic"
    },
    textLeft:{
        textAlign:"left"
    },
    textLowercase:{
        textTransform:"lowercase"
    },
    textMuted:{
        color:"#aaa"
    },
    textNoWrap:{
        whiteSpace:"nowrap"
    },
    textRight:{
        textAlign:"right"
    },
    textSmall:{
        fontSize:"0.8em"
    },
    textUppercase:{
        textTransform:"uppercase"
    }
};

export default helpers;